sudo: required

language: c

os: linux

dist: trusty

# compiler: sdcc

before_install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
  - sudo apt-get install -y curl subversion build-essential flex bison libboost-dev texinfo stx-btree-dev zip netcat gawk python2.7
  - mkdir sdcc-code -p
  - cd sdcc-code
  - svn checkout svn://svn.code.sf.net/p/sdcc/code/trunk/sdcc@10040
  - cd sdcc
  - ./configure --disable-mcs51-port \
                --disable-z80-port \
                --disable-z180-port \
                --disable-r2k-port \
                --disable-r3ka-port \
                --disable-gbz80-port \
                --disable-tlcs90-port \
                --disable-ds390-port \
                --disable-ds400-port \
                --disable-pic14-port \
                --disable-pic16-port \
                --disable-hc08-port \
                --disable-s08-port \
                --disable-ucsim \
                --disable-non-free
  - make && make install
  - cd ..
  - cd ..
  - rm -Rf sdcc-code

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - rm -r IntrOS-master

before_script: sdcc --version

script: make all SDCC= -f makefile.sdcc

group: stable
