os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
  - bash ./.build-sdcc.sh
  - sdcc --version

before_script:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv IntrOS-master/IntrOS/* IntrOS/
  - rm -r IntrOS-master

script: make all SDCC= -f makefile.sdcc
