sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install sdcc

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - rm -r IntrOS-master

before_script: sdcc --version

script: make all SDCC= -f makefile.sdcc

group: stable
