sudo: required

language: c

os: linux

dist: trusty

compiler: sdcc

before_install:
  - sudo apt-get update -qq
# - sudo apt-get install sdcc
# - wget https://netcologne.dl.sourceforge.net/project/sdcc/sdcc-linux-x86/3.6.0/sdcc-3.6.0-i386-unknown-linux2.5.tar.bz2
# - tar xjf sdcc-3.6.0-i386-unknown-linux2.5.tar.bz2
# - sudo cp -r sdcc-3.6.0/* /usr/local
# - rm -r sdcc-3.6.0
  - wget https://netcologne.dl.sourceforge.net/project/sdcc/snapshot_builds/amd64-unknown-linux2.5/sdcc-snapshot-amd64-unknown-linux2.5-20171007-10034.tar.bz2
  - tar xjf sdcc-snapshot-amd64-unknown-linux2.5-20171007-10034.tar.bz2
  - sudo cp -r sdcc/* /usr/local
  - rm -r sdcc

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip -O IntrOS-master.zip
  - unzip -q -d . IntrOS-master.zip IntrOS-master/IntrOS/kernel/*
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - rm -r IntrOS-master

before_script: /usr/local/bin/sdcc --version

script: make all SDCC=/usr/local/bin/ -f makefile.sdcc

group: stable
